#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KVS_android.Resource", IsApplication=true)]

namespace KVS_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_default_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edittext_bottom_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edittext_defealt_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edittext_top_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int linearlayout_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int schoolBackground = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int Klas = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int LogOut = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int Mede = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Plan = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int Settings = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int btnLogin = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnRegister = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int etEmail = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int etPass = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int etUserName = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int gridLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int loginButton = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int rInvoeren = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int rInzien = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int registerButton = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int action_settings = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int DefaultButtonText = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
